#CI for Product Catalog Service

name: product-catalog-ci

on: 
    pull_request:
        branches:
        - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
              
            - name:  Setup Go 1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22

            - name: Build
              run: |
                cd src/product-catalog
                go mod download
                go build -o product-catalog-service main.go

            - name: unit tests
              run: |
                cd src/product-catalog
                go test ./...

    code-quality::

        runs-on: ubuntu-latest

        steps:
          - name: checkout code
            uses: actions/checkout@v4
        
          - name: Run golangci-lint
            uses: golangci/golangci-lint-action@v6
            with:
              version: v1.55.2
              run: golangci-lint run
              working-directory: src/product-catalog
    
    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: Build Docker Image
            uses: docker/buildx-action@v2
        
          - name: Login to Docker
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}
